### ISSUE TITLE
Parametric bin appears to have top layer (not open/hollow)

### ISSUE THREAD

**Issue by Guy559** [Stu142/Freecad-dimension-variable-editing#1]
First off, thank you for your time in creating this design and for responding to this issue.

I dowloaded your design file, opened with FreeCAD, and used the spreadsheet to generate a 2x4x10 bin I'd like to print. However, whether I export as a .stl or .3mf file, Bambu Slicer opens as the part having a solid top covering (as opposed to being open air like a bin). 

Suspect I'm doing something incorrect with FreeCAD, though I've only changed 3 variables to generate this bin. Providing to you for awareness (in case model isn't hollow as designed) and for a specific way to print correctly.

Appreciate all.

<img width="911" alt="Screenshot 2023-12-04 at 8 23 37 AM" src="https://github.com/Stu142/Freecad-dimension-variable-editing/assets/95584030/2fc03889-302d-4e6c-8651-1e0f1deacf0b">

**Comment by Stu142** [comment]
That's interesting, what version did you download as I have a couple of different versions on printables and one is supposed to look like this so you can add custom cuts. If you are looking for just storage with no label shelf I don't have that currently but can easily add one when I get a chance. 

However, if it was the storage bit that you did download, make sure you select the body in the feature tree before exporting otherwise freecad will only export the feature you have selected. confirm the bin looks how you want before exporting. 

Another possible trouble shooting step would be to open the stl in freecad and see what it looks like there, it is the slicer or freecad.  

Its also possible there is an error in the model i will look into 

I plan to add a lot of this information to the guide but haven't had time yet.

**Comment by Guy559** [comment]
Yes, confirmed exporting correctly but when printing it's making it a solid piece, not hollow.  Using your file from Thangs: https://thangs.com/designer/Stu142/3d-model/FreeCAD%20Gridfinity%20Parametric%20Bin%20Blank.stl-965962

If you have a newer (or tested) version, please kindly point me that direction. Much appreciated.

Edit 1: At Thangs, when placed in 3D render view, you can see the issue--model is solid vice open.

Edit 2: Visited Printables in case model there is updated/different. Your Parametric Bin v2 (with label) is open air and models correctly. The other bin is solid and prints/models as a cube vice a bin. I believe your original model is my preferred design as I don't need a label lip or the sloped side for my current use. Seems it just needs to be hollowed out to be a bin vice a cube.

Thanks for the quick response and support.

**Comment by Guy559** [comment]
As a quick follow up: on Thangs, when placed in 3D render view, you can see that it's solid and not open

**Comment by Stu142** [comment]
That is how that one is supposed to look. I was able to make a quick modification for a storage bin without the label shelf:
[https://www.printables.com/model/670246-freecad-gridfinity-parametric-simple-storage-bin](https://www.printables.com/model/670246-freecad-gridfinity-parametric-simple-storage-bin)

**Comment by Guy559** [comment]
Thanks for doing so. Appreciate the support and quick turnaround. Heading to your page to make a donation.

**Comment by Stu142** [comment]
Thank you
